spring.application.name=claimService
server.port=8083

eureka.client.serviceUrl.defaultZone=http://localhost:8761/registry/eureka

spring.datasource.url=jdbc:postgresql://localhost:5433/Smart_Sure
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
